find_path(SNAPPY_INCLUDE_DIRS snappy.h "${LIBS_ROOT_DIR}")

find_library(SNAPPY_LIBRARIES snappy "${LIBS_ROOT_DIR}")

set(SNAPPY_FOUND TRUE)

if (NOT SNAPPY_INCLUDE_DIRS)
  set(SNAPPY_FOUND FALSE)
endif (NOT SNAPPY_INCLUDE_DIRS)

if (NOT SNAPPY_LIBRARIES)
  set(SNAPPY_FOUND FALSE)
endif (NOT SNAPPY_LIBRARIES)

