find_path(CPPUNIT_INCLUDE_DIRS Portability.h "${CPPUNIT_ROOT_DIR}")

find_library(CPPUNIT_LIBRARIES cppunit "${LIBS_ROOT_DIR}")

set(CPPUNIT_FOUND TRUE)

if (NOT CPPUNIT_INCLUDE_DIRS)
  set(CPPUNIT_FOUND FALSE)
endif (NOT CPPUNIT_INCLUDE_DIRS)

if (NOT CPPUNIT_LIBRARIES)
  set(CPPUNIT FALSE)
endif (NOT CPPUNIT_LIBRARIES)

