find_path(ZLIB_INCLUDE_DIRS zlib.h "${LIBS_ROOT_DIR}")

find_library(ZLIB_LIBRARIES z "${LIBS_ROOT_DIR}")

set(ZLIB_FOUND TRUE)

if (NOT ZLIB_INCLUDE_DIRS)
  set(ZLIB_FOUND FALSE)
endif (NOT ZLIB_INCLUDE_DIRS)

if (NOT ZLIB_LIBRARIES)
  set(ZLIB_FOUND FALSE)
endif (NOT ZLIB_LIBRARIES)

